# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19935782739d203424883c78dbda818dec77ee5030e2122c6cf489badb40779c16ebb0b0e2a66eba71db374c7308718d360ad3c5cb366973aa129afa6cc74e9a

test:
  secret_key_base: 2a9dba5046d06597540a8b01604a69ba2771cdc6fce8ae8711f6e23b76895ac9900381b696ad7fa7d1cfbc79cb9d00120fec5dbef09d8d6237c704dbe840f30b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
